server:
  port: 8080

mybatis-plus:
  mapper-locations: classpath*:com/hxk/meetingfilm/**/xml/*Mapper.xml
  global-config:
    id-type: 0
    db-column-underline: false
    refresh-mapper: true
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

spring:
  application:
    name: backend_meetingfilm
  datasource:
    url: jdbc:mysql://47.95.2.90:3306/meetingfilm?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=UTC
    username: root
    password: root
    filters: log4j,wall,mergeStat


logging:
  config: classpath:logback.xml


