server:
  port: 8080

mybatis-plus:
  mapper-locations: classpath*:com/hxk/meetingfilm/**/xml/*Mapper.xml
  global-config:
    id-type: 0
    db-column-underline: false
    refresh-mapper: true
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

spring:
  application:
    name: backend_meetingfilm
  datasource:
    url: jdbc:mysql://47.95.2.90:3306/meetingfilm?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=UTC
    username: root
    password: root
    filters: log4j,wall,mergeStat
  redis:
    database: 0
    host: 47.95.2.90
    port: 6379
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: 1
    timeout: 3000

# 图片服务器 minio配置
min:
  io:
    endpoint: "http://47.95.2.90:9000"
    accessKey: admin
    secretKey: 123123123
    bucket-name: test




logging:
  config: classpath:logback.xml


